### PR TITLE
Update `text` datetime to the following format: "17 Sep 2023 at 15:20"

### LINKED ISSUE #16: Should we display the time of messages as well, not just the date?
https://github.com/rafaelalmeidatk/nextjs-forum/blob/202ef7fc1124710383a1d8ecfb02b0085c320d9e/apps/web/utils/datetime.ts#L3-L7

Right now the timestamps in long form are displayed as dates only, e.g. "Jun 11". It seems this is an intentional decision, but shouldn't the time be displayed as well, e.g. "Jun 11 at 13:45"?

### PR DESCRIPTION
**Pull request by joulev**
~~It is now "9/1/2023, 4:07 PM" not "Sep 1". Though should we make it something like "Sep 1, 2023, 4:07 PM"?~~

image

Closes #16.

### CODE REVIEW

**Comment by RiskyMH** [comment]
Probably out of the scope of this PR, but could this be UTC-0 by default, and then the user's localized time?

**Comment by joulev** [comment]
@RiskyMH I think it is already in the user timezone, see [here](https://github.com/rafaelalmeidatk/nextjs-forum/blob/main/apps/web/components/local-time.tsx). I didn't test this PR though so I don't know.

**Comment by joulev** [comment]
hmm it seems to be behaving in sus ways, I think I have to test it locally now, can't just open PRs without testing all the time.

**Comment by RiskyMH** [comment]
Also, can you make it do dd/mm/yyyy if that is what the browser says as I don't like mm/dd/yyyy (idk if thats what sus thing is tho)

**Comment by joulev** [comment]
Since I'm making the effort to test this locally it *will* be "1 Sep 2023, 4:07 PM" because that's the only way that is not confusing to any locale systems.

**Comment by joulev** [comment]
Now I'll pray that I didn't mess up the timezones.

**Review by rafaelalmeidatk — COMMENTED** [review]
I like the changes for the post page itself but I think the time of cards on the home page are too long now. Can we apply this change only for the posts page?

**Review by rafaelalmeidatk — APPROVED** [review]
Thanks! Sorry for taking too long to merge this

**Pull request merged**
